//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Open_Schooling.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Open_Schooling_2025Entities : DbContext
    {
        public Open_Schooling_2025Entities()
            : base("name=Open_Schooling_2025Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<All_Taluka> All_Taluka { get; set; }
        public virtual DbSet<Center_Login_Information> Center_Login_Information { get; set; }
        public virtual DbSet<Tbl_Admin> Tbl_Admin { get; set; }
        public virtual DbSet<Tbl_Application_Form> Tbl_Application_Form { get; set; }
        public virtual DbSet<Tbl_BMM_Center> Tbl_BMM_Center { get; set; }
        public virtual DbSet<Tbl_CenterList> Tbl_CenterList { get; set; }
        public virtual DbSet<Tbl_District> Tbl_District { get; set; }
        public virtual DbSet<Tbl_OpenSch_Result> Tbl_OpenSch_Result { get; set; }
        public virtual DbSet<Tbl_PageStatus> Tbl_PageStatus { get; set; }
        public virtual DbSet<Tbl_payment> Tbl_payment { get; set; }
        public virtual DbSet<Tbl_Payment_Error> Tbl_Payment_Error { get; set; }
        public virtual DbSet<Tbl_Registration> Tbl_Registration { get; set; }
        public virtual DbSet<Tbl_result> Tbl_result { get; set; }
        public virtual DbSet<Tbl_Site_Status> Tbl_Site_Status { get; set; }
        public virtual DbSet<Tbl_Subject> Tbl_Subject { get; set; }
        public virtual DbSet<Tbl_AF_Backup> Tbl_AF_Backup { get; set; }
        public virtual DbSet<Tbl_Application_Form_bk> Tbl_Application_Form_bk { get; set; }
        public virtual DbSet<Tbl_Application_Form_Hallticket_bk> Tbl_Application_Form_Hallticket_bk { get; set; }
    }
}
