//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Open_Schooling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_BMM_Center
    {
        public int Id { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string State_Code { get; set; }
        public string Name { get; set; }
        public string Center_Code { get; set; }
    }
}
